### ISSUE TITLE
Setting up travis

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RSS-Textures#1]
@pjf I notice for RP-0 there's an api_key - how do I get one for this? Travis itself talks about _running_ travis itself...

**Comment by pjf** [comment]
That would be your [github settings](https://github.com/settings/tokens) for the token, and then I recall `travis encrypt` to encrypt it so you can safely pop it in your `.travis.yml` file without revealing it to others.

[This documentation](http://docs.travis-ci.com/user/deployment/releases/) may help.

**Comment by NathanKell** [comment]
Right. travis is ruby? I think I have ruby...

**Comment by pjf** [comment]
The Travis command line is ruby, aye. "gem install travis" should hopefully get you what you need.

I also anticipate being back from travels in a few hours and can lend a hand. It's very much in my interests to make it easier for RSS to make releases. :-)

**Comment by NathanKell** [comment]
@pjf the build worked that time! :)

**Comment by pjf** [comment]
Aww yis. Let's hope it continues to work for future releases.

Worst comes to worst we establish a release hook that gets our own system to build and package the release, but if travis can do the right thing I'll be delighted. :)
