### ISSUE TITLE
Pluto Maps

### ISSUE THREAD

**Issue by Felger** [KSP-RO/RSS-Textures#10]
Found these, I'm sure they'll be improved later, but they'd make a good starting place!  
http://www.unmannedspaceflight.com/index.php?act=attach&type=post&id=37232
http://www.unmannedspaceflight.com/index.php?act=attach&type=post&id=37083

**Comment by NathanKell** [comment]
Awesome! :)

**Comment by NathanKell** [comment]
Done by @KillAshley
