### ISSUE TITLE
Please update to be compatible with V1.1.3.1289 

### ISSUE THREAD

**Issue by edward3709** [KSP-RO/RSS-Textures#14]
I really enjoyed these textures but now I cant because it isn't compatible with version 1.1.3. Please update it so I can use these textures for the new version.

Thank you

**Comment by NathanKell** [comment]
Please explain. Works fine in 1.1.3, metadata on CKAN supports that too.

**Comment by edward3709** [comment]
When I downloaded the 4096 texture with Real Solar System mod when I opened my KSP, it was with the default ksp textures with V1.1.3.

**Comment by edward3709** [comment]
It works now, sorry for the inconvenience

**Comment by NathanKell** [comment]
Cool!
