### ISSUE TITLE
[Bug] Saturn ring texture rotation

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RSS-Textures#15]
Kopernicus, with the help of Scatterer, now allows the rings to be shaded correctly (no more fullbright rings). The RSS ring needs to be updated but the edit is a small one: rotate the ring texture 90 degrees counter-clockwise. This will allow the ring to operate with both "stock" Kopernicus and with the Kopernicus/Scatterer combo.

**Edit:** also, the current ring texture is oriented incorrectly: the F ring is in the place of the D ring (requires a 180 degree flip).

**Comment by PhineasFreak** [comment]
This is probably a moot point now since the next Kopernicus update will now accept both texture orientations (PR https://github.com/Kopernicus/Kopernicus/pull/206). Still, the texture should be flipped in order to fix the F and D rings.

**Comment by Bornholio** [comment]
Simple flip along y axis and re-mipmap?  or Kopernicus .cfg edit?

**Comment by PhineasFreak** [comment]
Yep, just a texture flip.

**Comment by PhineasFreak** [comment]
Fixed in https://github.com/KSP-RO/RSS-Textures/pull/18.
