### ISSUE TITLE
Todo: Get height/normal maps for added bodies

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RSS-Textures#2]
We only have color maps for the Saturnian moons and Triton, and we don't have anything for Charon.

**Comment by Bornholio** [comment]
Currently all bodies have full set of color/normal/height/biome except (* = Gas Giant so no Heigh/Normal Needed?) 

1. Dione
2. Enceladus
3. Iapetus
4. Jupiter* (should have minor ring)
5. Mimas
6. Neptune* (should have minor ring)
7. Rhea
8. Saturn* (Has Ring)
9. Tethys
10. Triton
11. Uranus* (should have minor ring)

**Comment by raidernick** [comment]
yes this is old well before any of the recent changes, it can be closed like the rest, upon release.

**Comment by PhineasFreak** [comment]
I'd argue that the Jupiter and Neptune rings are so faint IRL that it would not be possible to directly observe them (assuming that the camera view point operates like a human eye). But, if you want to add them then [RSSExpansion](https://github.com/PhineasFreak/RSSExpansion) (sameless plug...) already has the textures and it is easy to implement them.

**Comment by raidernick** [comment]
https://github.com/KSP-RO/RSS-Textures/releases/tag/v13.0
