### ISSUE TITLE
KSP stuck on loading screen

### ISSUE THREAD

**Issue by ghost** [KSP-RO/RSS-Textures#24]
I installed everything correctly yet the when I load up KSP it stays stuck on the loading screen. I removed RSS and RSS Textures and the game loads fine. When I add these in it gets stuck. I also downloaded all the dependencies for it and they load just fine with the game but RSS will not

**Comment by joaocosta-azores** [comment]
Same issue here with KSP 1.6.1. Is that the version you are running?
It happens when I install [RealSolarSystem](RealSolarSystem), it's before I install RSS-Textures.

**Comment by joaocosta-azores** [comment]
I've installed RSS Texture 2048 and no more stuck on loading. The problem now is with main station, it's too dark. Other complex seems ok.
![Screenshot 2019-04-06 at 11 25 49](https://user-images.githubusercontent.com/2188826/55668987-3a9dc180-5861-11e9-801d-7807d6241370.png)

**Comment by PhineasFreak** [comment]
Timewarp until the sun is higher in the sky...

**Comment by raidernick** [comment]
sigh...
