### ISSUE TITLE
Todo: New biomes for Earth

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RSS-Textures#3]
Earth's biomes are...poor. We should be using a setup [more like this](https://www.marietta.edu/~biol/biomes/biomemap.jpg), say, and we should have them in at least 4096. The only additions I'd make to that map are to add a shore biome that covers coastlines, so you get 'shore' about 2-3km out to sea and about 2-3km inland, so you don't keep getting 'grassland' 5km out in the ocean (!).or water inland. Second addition: "Urban", based off the city lights mask.

**Comment by KellanHiggins** [comment]
Working on this now, will have a new version very soon.

**Comment by NathanKell** [comment]
@KellanHiggins awesome, thanks! :)

**Comment by KellanHiggins** [comment]
Here is my first pass at it. I don't like the colours, so I may change them soon. I've put in 12 biomes. Rainforest, Mountain, Shores, Water, Deserts, Tropical, Arctic, Antarctic, Woodland, Taiga, Highlands and Islands.

If this looks good, I'll redo the colors to be more appealing and copy paste the color values for the biomes.

Let me know if this looks good!

![newrssbiomes-4096](https://cloud.githubusercontent.com/assets/5897704/8704610/d5b16722-2ad8-11e5-8670-2a1342ca64a1.png)

**Comment by xiombargdei** [comment]
wow it looks very neat ! much more natural than mine. I hadn't touch the Gimp in ages though ;)

![earthbiomes_endroit](https://cloud.githubusercontent.com/assets/13231642/8706712/9274944e-2b31-11e5-94a2-48a00464d54d.png)

I think i'll be doing Neptune and maybe Triton tomorow. Would you like to look at some of Saturn's moon ?

**Comment by NathanKell** [comment]
@KellanHiggins looks solid!
For colors, I should mention how KSP works (if you're not familiar). There's bilinear filtering on the pixels, and CBAttributeMapSO picks the attribute that has color values closest to the pixel. That means you have to be somewhat careful with colors that border one another such that the result of the filtering isn't a third biome (i.e. a bit of coastal between desert and highlands). I am not quite awake enough to work out the graph-theoretical implications of that, but I think you'll figure it out. :)
For orientation, note that the biome map does need to be oriented as the surface maps are, i.e. flipped horizontal and offset (starting with Longitude 0 = middle of image) 1/4 width to the left. Since you based this off the surface map anyway, that should be easy enough to revert the orientation changes.

**Comment by Felger** [comment]
Another useful thing to do is use the heightmap and use GIMP's tools to mark out topographical lines to get a more natural-looking biome edge.

**Comment by KellanHiggins** [comment]
Do you think I should grab the colour mapping from the kerbin biomes? Use that instead.

As for the filtering, there is no AA between the biomes except on the shores (which are black). I think that should work fine. @xiombargdei, hope you don't mind if I put more work into mine. I made everything in vectors, so I can quickly update the colour scheme.

@Felger, I am using Photoshop. I'll look into using the heightmaps to add contours.

![uk3b1s2](https://cloud.githubusercontent.com/assets/5897704/8714796/f17dfbc8-2b2d-11e5-8bf3-456b6de3e889.png)

**Comment by NathanKell** [comment]
@KellanHiggins Beyond eight biomes there can no longer be strictly independent colors, so any further colors should be chosen with care as to what they're going to be next to. Since no stock biome maps need to worry about that, AFAIK, (all <= 8 biomes)...beyond those 8 'primary' colors (0,0,0, 255,0,0, etc) is up to you to figure what's best.As to filtering, I was talking about how CBAttributeMapSO works, not how your image works. :)
What might work well is if, say, the shore/coastal biome color was 0,128,255 and water was 0,0,255 and Mountains was 0,255,0, and things that bordered Mountains also had 0 in the blue channel. That should ensure that coast color will not easily be created by a lerp between something else and water, or something else and mountain. I think.
If it's vector, did you make it from an existing Earth vector map, or do you only mean the biome mapping? Because the map would need to conform to the earth surface and heightmap textures or things will be a bit odd. :)

Thanks again! :)

**Comment by KellanHiggins** [comment]
Here are the final versions produced. Some issues around arctic biome appearing in the Himalayas and the Andes, but it looks prettier than sold colors. Happy to revise at a later date. Or we can just use the solid color one.

The color values used are the default ones for Kerbal, with the exception of badlands who have become Tropics.

Here are the biomes I put in. Mountains are hard to get because they aren't easily on any launch path and very small.

``` javascript
            {
                Biome
                {
                    name = Grasslands
                    value = 1.0
                    color = 61,105,46,1
                }
                Biome
                {
                    name = Highlands
                    value = 1.0
                    color = 26,80,44,1
                }
                Biome
                {
                    name = Mountains
                    value = 2.0
                    color = 97,68,64,1
                }
                Biome
                {
                    name = Desert
                    value = 1.5
                    color = 138,110,30,1
                }
                Biome
                {
                    name = Tropics
                    value = 1.0
                    color = 19,29,21,1
                }
                Biome
                {
                    name = Poles
                    value = 1.5
                    color = 186,186,186,1
                }
                Biome
                {
                    name = Water
                    value = 1.0
                    color = 0,50,132,1
                }
                Biome
                {
                    name = Shores
                    value = 1.0
                    color = 223,72,193,1
                }

            }
```

![newrssbiomesfinal-8192](https://cloud.githubusercontent.com/assets/5897704/8718023/7cb27d00-2b55-11e5-9a15-6ded23ad4d2e.png)
![newrssbiomesfinal-4096](https://cloud.githubusercontent.com/assets/5897704/8718024/7cb4a558-2b55-11e5-8a95-5566c26986ee.png)
![newrssbiomesfinal-2048](https://cloud.githubusercontent.com/assets/5897704/8718025/7cb64a7a-2b55-11e5-8287-e01d7eb617ed.png)

EDIT: Added markdown.

**Comment by KellanHiggins** [comment]
Oh and these are built using pixeled images of the earth that should align with what I had before AND then all the biomes are vectorized in an illustrator file.

**Comment by NathanKell** [comment]
@KellanHiggins did you ever get the install working? I'm going to hook this up in RSS but if it's causing problems we need to get them sorted. :)

**Comment by KellanHiggins** [comment]
I think the blitzy toolbar was causing issues because it hasn't been updated to work in 1.04 yet. Anyways did get it to work, but then found some science issues. Need to do more testing as I've probably installed too many mods with Ckan.

Everything runs find without RP-0, things start getting screwy once I install that.

**Comment by NathanKell** [comment]
@KellanHiggins ah, ok. I'm currently trying to get RP-0 contracts working, but it continues to load at least, at least for me. Weird. :\
As to the map--you decided on 8 rather than 12, I take it? I have no problem with the extra biomes, btw, and I'm sure colors can be chosen to make it work fine.

**Comment by KellanHiggins** [comment]
I chose 8 biomes to make it simpler so I didn't have to wrap my head around Lerping between colours. Besides, less biomes means the player needs to get into the Solar System to get more science. The 12 biomes I had originally are still vectorized and can be added in easily later.

**Comment by NathanKell** [comment]
@KellanHiggins sorry, got buried in other stuff. I'll try to plug this in today. Can you upload pure-color versions in the three sizes? Though have relief shading on them, it looks like? (i.e. check out what the existing RSS biome maps look like, pure colors everywhere...)

**Comment by KellanHiggins** [comment]
Done with solid colors. Thought I had to add relief to make it look good. I've also updated the colors for the biome maps. They are below.

```
{
                Biome
                {
                    name = Grasslands
                    value = 1.0
                    color = 89,200,15,1
                }
                Biome
                {
                    name = Highlands
                    value = 1.0
                    color = 120,226,102,1
                }
                Biome
                {
                    name = Mountains
                    value = 2.0
                    color = 130,70,0,1
                }
                Biome
                {
                    name = Desert
                    value = 1.5
                    color = 245,188,0,1
                }
                Biome
                {
                    name = Tropics
                    value = 1.0
                    color = 6,37,9,1
                }
                Biome
                {
                    name = Poles
                    value = 1.5
                    color = 254,254,254,1
                }
                Biome
                {
                    name = Water
                    value = 1.0
                    color = 0,50,132,1
                }
                Biome
                {
                    name = Shores
                    value = 1.0
                    color = 239,43,239,1
                }

            }
```

![earthrssbiomes-2048](https://cloud.githubusercontent.com/assets/5897704/8856362/2f38fc46-311f-11e5-9824-73e139c14160.png)
![earthrssbiomes-4096](https://cloud.githubusercontent.com/assets/5897704/8856364/2f470eda-311f-11e5-9687-bfe01cf6ba45.png)
![earthrssbiomes-8192](https://cloud.githubusercontent.com/assets/5897704/8856363/2f425976-311f-11e5-9e97-2cfec85180c0.png)

EDIT: Markdown.

**Comment by NathanKell** [comment]
@KellanHiggins  I've been playing with the new biome, and ran into an issue. I first converted all the 0-255 colors to float (which Kopernicus wants), then have been trying it out. It appears that the various green colors (as well as shore (!) ) are too close in hue to the Grasslands color--I don't switch to highlands or tropics at all, it seems, and shores are finicky. Can you test it on your end and make sure you get all the biomes correctly (MJ, for example, can tell you what biome you're over, probably KER can too).

**Comment by NathanKell** [comment]
Ah, and the other issues (though I've mostly corrected them in the 2048 I committed) are:
- on the 2048 the band of shore is too narrow--and probably in terms of being able to hit it when in orbit it's always too narrow. I'd suggest doubling it, and applying it to lakes (and any other "water" pixel from the color map's alpha channel that isn't already biome 'Water')
- Had to offset the 2048 map 4 pixels right to align with the color and heightmaps. That'd be 8 and 16 for 4096 and 8192 maps, I think, though they may need a finer alignment.

**Comment by KellanHiggins** [comment]
@NathanKell sorry for the delay, haven't been checking this. Should I download the latest release of RSS and test like that?

Do you want me to redo the 2048 map to have larger shores? I can also offset all the maps by the suggested amount if you'd like as well. Let me know.

**Comment by NathanKell** [comment]
@KellanHiggins  &(%@ I thought I replied. Sorry!
Grab RSS from the repo, that has the new biomes.

Yes, it'd be great if you could enlarge the shores a bit so there's a consistent band even at 2048, and offset such that the biome map aligns with the similarly-sized heightmap (for 2048 that appears to be about 4 pixels' offset, at least near the Cape).

I'm really sorry about this, coulda sworn I replied. I'm going to go ahead and release with the 2048 that's in the repo now, and then release again with the full suite when you get done, because I'm shortly not going to have the best connection and travis hasn't been super-awesome about building these properly.

**Comment by KellanHiggins** [comment]
All good, I made it in Illustrator so its pretty easy to change.

Which way should I offset? Vertical or Horizontal? I've been swamped with my real job and haven't had the time to open up the game for testing.

I'll also take a look at the new colors and modify my version to fit those (If you changed them).

**Comment by NathanKell** [comment]
I offset the final 2048 image four pixels right. You can just do it when you make your single offset, though, that means your left offset should be (1/4 the width - 1/512 the width, i.e. 512-4=508 for a 2048 width image) when you do your left offset. But best is to load up the existing heightmap and try for a best-fit, the 4 was "good enough" rather than necessarily perfection.

I have not changed the colors, but I would suggest using the original RSS Earth biome colors (with 8 biomes every biome color can have either 0 or 255 in each channel). That makes the game's life easier.

Thanks again! :)

**Comment by KellanHiggins** [comment]
But holy cow those colors are horrible on the eyes. Red! That is crazy. I will try and figure something out.

I have a Mac and therefore I don't think loading up the heightmap will work. Unless you are saying I can do it in Unity? Sorry for all the questions! This is new territory to me.

**Comment by NathanKell** [comment]
They are horrible, yes...but machines gonna machine. :P

There should be something that will open, or convert, DDS on the Mac; failing that I can convert and upload as png. And no worries! :)
(I mean the heightmaps in this repo, in case that wasn't clear--they're in (resolution)/PluginData)

**Comment by KellanHiggins** [comment]
So sorry, completely dropped off the end of the earth. Finally got back into KSP, I see the new biomes are working great. :)

**Comment by NathanKell** [comment]
They are! Thank you so much!
(I kinda dropped off too, as you can see--it's been some very busy times with 1.0.5)

**Comment by gazpachian** [comment]
Alright, there are certainly pros and cons with what I've got here, so I'll leave it to you whether the Earth biome map needs further adjustments (I'm already figuring it doesn't and you've just forgotten to close the issue). The map is based on the current biome map (using the same colors for each biome et.c.) but uses data directly from height and precipitation maps rather than vectorized approximations. Some corrections have been made to the resulting map, such as making sure Antarctica and Greenland had any other biome on them other than mountains.

![earthbiomes](https://cloud.githubusercontent.com/assets/3220774/16350162/68dd00da-3a5d-11e6-869a-ff660e4ee62b.png)

**Pros:**
Launch sites in mountainous areas (Xichang, CN for example) should actually be near the mountains biome.

Highlands in Scotland! _<- this is the big one, right here_
All land biomes except poles present on every continent (for certain definitions of continent).
Grasslands less prominent in non-temperate climates, but still within reach from most launch sites.

**Cons:**
More biome "flickering" in orbit.
Larger download size (more detail = harder to compress)

Overall the biomes are roughly in the same place in both versions of the map so it's of no major importance. The reason I made my own version is that I felt the provided one looked a bit arbitrary. Having reconstructed it from real data myself it appears that mr. Higgins has done a great job and it probably comes down to personal preference to say whether my version is "better" or simply not worth the larger file size/ScienceAlert spam generation.

But I've already made it, so I figured I may as well post it here for your consideration!

**Comment by KellanHiggins** [comment]
@gazpachian I like yours better, really enjoy the more detail. I think we should go with it. To make my biome I pulled a biome map of the world and drew over it. Probably why it is semi good.

I am somewhat certain my biomes got pulled in an update by @NathanKell. Not sure why but not offended. Hope we can get this one in there!

**Comment by NathanKell** [comment]
@gazpachian Yep, I like that. :) I agree with breaking things up as possible. Also worth checking to make sure that things line up in flight?

@KellanHiggins not sure why you might think that, since it isn't true. :P
See https://github.com/KSP-RO/RSS-Textures/blob/master/Biomes/EarthBiomes.png

**Comment by KellanHiggins** [comment]
Then I am going totally crazy. Nevermind. While I've got you, whats up with FASA? I just got a beast of a computer and wanna play my old 1.0.4 game but FASA seems outdated now.

**Comment by gazpachian** [comment]
@NathanKell I haven't done any extensive tests in flight with it (no access to my trusty desktop for a couple days more at the least) but at least as far as shorelines go those are copied straight off the current biome map, I.E. the water and shores biomes should be in exactly the same locations as before. As long as those are where they are supposed to be I figured most cases of "_it looks like I'm over x but it says that I'm over y_" would already be dealt with. So, are we content with the locations of those biomes as is or do they need further fine tuning/offset?

**Comment by NathanKell** [comment]
@gazpachian they're sometimes wrong. I had to offset the map a few pixels IIRC and that fixed a lot of it, but there are still some offsets between terrain ingame and biome. Play without RVE and turn on Alt-F12->Show biomes to see better.

**Comment by Bornholio** [comment]
with Pap's Scaled RSS and dev biome map changes should we return to this topic or Close?

**Comment by raidernick** [comment]
yep it can be closed as soon as we release.

**Comment by raidernick** [comment]
https://github.com/KSP-RO/RSS-Textures/releases/tag/v13.0
