### ISSUE TITLE
EarthHeight.dds file in 8192.zip for v18.2 release is missing content.

### ISSUE THREAD

**Issue by pt1243** [KSP-RO/RSS-Textures#37]
As per the title, the EarthHeight.dds file in the 8192 resolution release is only 1KB in size, compared to the ~16MB for the 2048 textures release - looks like the wrong file has been attached to the release. 

Log spam of null reference exceptions and KSP stuck on black loading screen when loading a save. I can provide logs if needed.

**Comment by RCrockford** [comment]
The release has been updated - it should have a correct Earth heightmap in now.
Thanks for the report.
