### ISSUE TITLE
EarthHeight.dds and other heightmaps missing in 8192 and 16384 folders

### ISSUE THREAD

**Issue by JebediahKermanKSP** [KSP-RO/RSS-Textures#46]
Just like the title said, Heightmap textures missing in 8192 and 16384 folders. Plus, some Color maps are also missing in the 16384 folder.

**Comment by siimav** [comment]
Well, yes. The texture sizes are over the limits that GH supports for files. We also tried Git LFS at some point but the usage terms that GH has for that feature is completely unfit for public repos. For now the large texture files will have to stay in the release zips only.
