### ISSUE TITLE
Settings question

### ISSUE THREAD

**Issue by bymaximus** [KSP-RO/RSS-Textures#49]
Hello guys, simple question, does selecting KSP textures settings to low while having the RSS 16K textures installed will still make use of the RSS 16K textures?

**Comment by siimav** [comment]
Yes, it does. RSS can only have one size of textures installed at a time. You would need to delete 16k and install 8k (or smaller) if those consume too much memory.

**Comment by bymaximus** [comment]
The memory usage is related to VRAM or RAM? 
I see it takes really long time to load for me while using 16K version compared to 2K version, I have 26gb ram, 4gb gpu, ssd hd.

I also saw one time (while testing) at KSP graphics settings (texture option) it had some 'RSS High' (preset i think), so, I can change the KSP texture quality settings to low but the RSS textures will be still being used or I need to keep the RSS option selected?

**Comment by siimav** [comment]
Yes, texture size will affect both VRAM and system RAM usage although it's pretty normal for VRAM to be close to 100% utilized.
'RSS High' or 'New Text' shown in the KSP settings doesn't matter at all.

**Comment by bymaximus** [comment]
Awesome, thanks
