### ISSUE TITLE
Phobos and Deimos look incorrect on the tracking screen

### ISSUE THREAD

**Issue by grayduster** [KSP-RO/RSS-Textures#8]
Raising this here instead of RSS, as you don't seem to be able to raise issues on that repo.

Examples:

http://imgur.com/a/ysvwT

**Comment by grayduster** [comment]
Also, I was just looking at the Biomes for these two - Deimos and Phobos biome maps don't seem to match up with the Deimos and Phobos colour (both were existing before I started contributing) - if you flip either the biome or colour _vertically_, then they match up.  Is this vertical flip intentional and if not, which one needs flipping?

**Comment by Felger** [comment]
I made the biome map, if I had to guess, I'd guess the biome map is upside down, though vertical swap is strange.  The more common bug was to forget to flip horizontally...

**Comment by grayduster** [comment]
Thanks @Felger - I'll flip them vertically and commit - assuming there's no weird reason going on as to why biomes need vertical flipping :)

That still leaves the tracking screen view of the moons, so I'll leave this open.

**Comment by Felger** [comment]
@NathanKell should comment, make sure the texture itself isn't accidentally
flipped.  But I made the biome maps from the original body textures, so it
should be oriented the same as the body texture, unless I did something
extraordinarily bizarre in my image editing.
