### ISSUE TITLE
Travis issues

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RSS-Textures#9]
@pjf for deploying 10.0, 2048 came up the first time but nothing else. Restarting the build eventually put 8192 up, but I'm having to upload 4096 manually (build had no errors, but on 'editing' the release on github, github said the 4096 zip was bad and to delete and reupload, so I'm doing that).

**Comment by Bornholio** [comment]
This is no longer a issue?

**Comment by raidernick** [comment]
considering this is from 2015, I'm going to say no. I'll wait until we make the new release and if everything goes up ok, we will close this.

**Comment by raidernick** [comment]
https://github.com/KSP-RO/RSS-Textures/releases/tag/v13.0
